[workspace]

members = [
    "func_metadata",
    "func_proc",
    "func_struct"
]

resolver = "3"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
